Band.create [   
    { name: "Guns n' Roses", genre:"Rock"},
    { name: "Black Sabbath", genre:"Rock"},
    { name: "Creedence Clearwater Revival", genre:"Rock"},
    { name:"Simon and Garfunkel", genre:"Rock"},
    { name:"Led Zeppelin", genre:"Rock"},
    { name:"Public Enemy", genre:"Hip Hop"},
    { name:"OutKast", genre:"Hip Hop"},
    { name:"Cypress Hill", genre:"Hip Hop"},
    { name:"Beastie Boys", genre:"Hip Hop"},
    { name:"A Tribe Called Quest", genre:"Hip Hop"},
    { name:"Eminem", genre:"Hip Hop"},
    { name:"Florence and the Machine", genre:"Indie"},
    { name:"Marina and the Diamonds", genre:"Indie"},
    { name:"Sylvan Esso", genre:"Indie"},
    { name:"Santigold", genre:"Electronic"},
    { name: "The Civil Wars", genre: "Folk"},
    { name: "Phantogram", genre: "Electronic"}
]


MusicVideo.create [ 
    {song_title: "Heavy In Your Arms", band_id: 12, video_embed_url: "V_eOmvM-4zc"},
    {song_title: "Disparate Youth", band_id:15, video_embed_url: "mIMMZQJ1H6E"},
    {song_title: "God From The Machine", band_id:15, video_embed_url: "wDPIp_zZG40"},
    {song_title: "Dress", band_id:14, video_embed_url: "N-L8EkHIHpI"},
    {song_title: "Dreamy Bruises", band_id:14, video_embed_url: "B5JZNWxBBMA"},
    {song_title: "November Rain", band_id:1, video_embed_url: "bzT4X6EYdKc"},
    {song_title: "Welcome To The Jungle", band_id:1, video_embed_url: "o1tj2zJ2Wvg"},
    {song_title: "Don't Cry", band_id:1, video_embed_url: "zRIbf6JqkNc"},
    {song_title: "Barton Hollow", band_id:16, video_embed_url: "ExAM8D7cfbI"},
    {song_title: "Tip Of My Tongue", band_id:16, video_embed_url: "H-RtrpwIME0"},
    {song_title: "The One That Got Away", band_id:16, video_embed_url: "MnkM_ebv9BI"},
    {song_title: "Blue", band_id:13, video_embed_url: "gDr7aTfBffU"},
    {song_title: "Oh No!", band_id:13, video_embed_url: "Cr-SqRWImmI"},
    {song_title: "No Sleep Til Brooklyn", band_id:9, video_embed_url: "07Y0cy-nvAg"},
    {song_title: "Iron Man", band_id:2, video_embed_url: "5c5xZFUq04w"},
    {song_title: "Black Out Days", band_id:17, video_embed_url: "a0ul-BghOAs"},
    {song_title: "Fall In Love", band_id:17, video_embed_url: "RsQjC5zVnt8"},
    {song_title: "Phenomenal", band_id:11, video_embed_url: "oeCihv9A3ac"},
    {song_title: "Electric Relaxation", band_id:10, video_embed_url: "WHRnvjCkTsw"},
    {song_title: "Illusions", band_id:8, video_embed_url: "xnFj5-ZBk1g"},
    {song_title: "Roses", band_id:7, video_embed_url: "gWju37TZfo0"},
    {song_title: "The Way You Move", band_id:7, video_embed_url: "xI5NQ-0Ubfs"},
    {song_title: "When The Levee Breaks", band_id:5, video_embed_url: "WbrjRKB586s"},
    {song_title: "Battle of Evermore", band_id:5, video_embed_url: "y_CfbR0F_wk"},
    {song_title: "Can't Truss It", band_id:6, video_embed_url: "am9BqZ6eA5c"},
    {song_title: "Don't Believe The Hype", band_id:6, video_embed_url: "9vQaVIoEjOM"},
    {song_title: "Born On The Bayou", band_id:3, video_embed_url: "fcTQCNntGEs"},
    {song_title: "The Sounds of Silence", band_id:4, video_embed_url: "4fWyzwo1xg0"},
    {song_title: "Can I Kick It", band_id:11, video_embed_url: "71ubKHzujy8"}
]
